# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=16)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('qty', models.CharField(default=0, max_length=8, null=True)),
                ('in_stock', models.CharField(blank=True, default=0, max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('free_shipping', models.BooleanField(max_length=32)),
                ('date_updated', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=None, max_length=128, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
